//go:build lua547

package lua

/*
#cgo CFLAGS: -I ${SRCDIR}/glue
#cgo windows,lua547 LDFLAGS:
#cgo linux,lua547 LDFLAGS: -lm
#cgo windows,lua547 CFLAGS: -I ${SRCDIR}/lua547
#cgo linux,lua547 CFLAGS: -I ${SRCDIR}/lua547
#include "lapi.c"
#include "lapi.h"
#include "lauxlib.c"
#include "lauxlib.h"
#include "lbaselib.c"
#include "lcode.c"
#include "lcode.h"
#include "lcorolib.c"
#include "lctype.c"
#include "lctype.h"
#include "ldblib.c"
#include "ldebug.c"
#include "ldebug.h"
#include "ldo.c"
#include "ldo.h"
#include "ldump.c"
#include "lfunc.c"
#include "lfunc.h"
#include "lgc.c"
#include "lgc.h"
#include "linit.c"
#include "liolib.c"
#include "llex.c"
#include "llex.h"
#include "llimits.h"
#include "lmathlib.c"
#include "lmem.c"
#include "lmem.h"
#include "loadlib.c"
#include "lobject.c"
#include "lobject.h"
#include "lopcodes.c"
#include "lopcodes.h"
#include "lopnames.h"
#include "loslib.c"
#include "lparser.c"
#include "lparser.h"
#include "lprefix.h"
#include "lstate.c"
#include "lstate.h"
#include "lstring.c"
#include "lstring.h"
#include "lstrlib.c"
#include "ltable.c"
#include "ltable.h"
#include "ltablib.c"
#include "ltm.c"
#include "ltm.h"
#include "lua.h"
//#include "lua.hpp"
#include "luaconf.h"
#include "lualib.h"
#include "lundump.c"
#include "lundump.h"
#include "lutf8lib.c"
#include "lvm.c"
#include "lvm.h"
//#include "ljumptab.h"
#include "lzio.c"
#include "lzio.h"
*/
import "C"